blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Feature Requests & Questions 
    url: https://github.com/tinyplex/tinytick/discussions
    about: Please ask and answer questions here.
  # - name: ðŸ’¬ Community Chat {Discord, Slack etc..} Channel 
  #   url: ...